# USC EE569 Homework Assignments
# Date: Feburary 5, 2017
# Name: Xuejing Lei
# Email: xjlei1117@gmail.com
#
# compiled on ubuntu 16.04 (x86_64 Linux)
# with gcc version 5.4.0

basic:
	echo "basic functions: "
	echo "comiling and linking the code"
	g++ -o basic_func_mrc basic_func_mrc.cpp
	./basic_func_mrc dog beach
	g++ -o basic_func_CSTLB basic_func_CSTLB.cpp
	./basic_func_CSTLB parrot building cat dolphin beach top_layer bottom_layer
histogram:
	echo "histogram related functions: "
	echo "comiling and linking the code"
	g++ -o hist_equa_gray hist_equa_gray.cpp
	./hist_equa_gray tulip_dark tulip_bright tulip_mix
	g++ -o hist_equa_color hist_equa_color.cpp
	./hist_equa_color bedroom
	g++ -o hist_trans hist_trans.cpp
	./hist_trans forest_1 forest_2
denoising:
	echo "denoising: "
	echo "comiling and linking the code"
	g++ -o denoising_basic_filters denoising_basic_filters.cpp
	./denoising_basic_filters pepper_noisy pepper sailboat_noisy sailboat
	g++ -o denoising_NLM denoising_NLM.cpp
	./denoising_NLM pepper_noisy pepper sailboat_noisy sailboat
geommatch:
	@echo "geometrical matching: "
	@echo "comiling and linking the code"
	g++ -o geom_warp geom_warp.cpp
	./geom_warp cup1 cup2
puzzlematch:
	@echo "puzzle matching: "
	@echo "comiling and linking the code"
	g++ -o puzzle_match puzzle_match.cpp
	./puzzle_match piece Hillary Trump
homogtrans:
	@echo "homographic transformation and image overlay: "
	@echo "comiling and linking the code"
	g++ -o homog_trans homog_trans.cpp
	./homog_trans field tartans trojans
halftoning:
	@echo "digital halftoning:"
	@echo "comiling and linking the code"
	g++ -o halftoning halftoning.cpp
	./halftoning man
morphproce:
	@echo "morphological processing："
	@echo "comiling and linking the code"
	g++ -o morph_proce morph_proce.cpp
	./morph_proce squares letterE board

